### ISSUE TITLE
NoMethodError

### ISSUE THREAD

**Issue by praveenbysani** [sul-dlss/blacklight-hierarchy#1]
Hi: 

I tried to install the plugin according to the instructions, on the demo application distributed by BL . I am using ruby 1.9.3 and BL 3.2. But the following error persits when the server is deployed,

undefined method `each' for nil:NilClass

Extracted source (around line #2):

1: <ul class="facet-hierarchy">
2:   <%= raw(render_hierarchy(facet_field)) %>
3: </ul>

Trace of template inclusion: app/views/catalog/_facets.html.erb, /home/praveen/.rvm/gems/ruby-1.9.3-p0/gems/blacklight-3.2.2/app/views/catalog/_home.html.erb, /home/praveen/.rvm/gems/ruby-1.9.3-p0/gems/blacklight-3.2.2/app/views/catalog/index.html.erb

**Comment by jcoyne** [comment]
I'm closing because this is stale. If still an issue please re-open.
