### ISSUE TITLE
Configuration drift

### ISSUE THREAD

**Issue by atz** [sul-dlss/blacklight-hierarchy#4]
README describes a different configuration than inline docs and code expect.

``` ruby
config.facet_display = {
  :hierarchy => {
    'tag' => [nil]
  }
}
```

vs.
https://github.com/sul-dlss/blacklight-hierarchy/blob/master/app/helpers/blacklight/hierarchy_helper.rb#L64-L69

``` ruby
config.facet_display = {
  :hierarchy => {
    'wf' => [['wps','wsp','swp'], ':'],  # values are arrays: 1st element is array, 2nd is delimiter string
    'callnum' => [['top_facet'], '/']
  }
}
```

The former results in errors like:

```
 undefined method `each' for "wps":String
 # /Users/atz/.rvm/gems/ruby-1.9.3-p547/gems/blacklight-hierarchy-0.1.0/app/helpers/blacklight/hierarchy_helper.rb:78:in `facet_tree'
```

The latter, if delimiter arg is not specified:

```
can't convert Array to String
# /Users/atz/.rvm/gems/ruby-1.9.3-p547/gems/blacklight-hierarchy-0.1.0/app/helpers/blacklight/hierarchy_helper.rb:75:in `escape'
```

A reasonable default delimiter value should be provided.

Also facet_tree should be decomposed for testability.

**Comment by ndushay** [comment]
I updated README with 3c584f46 to be in line with code comments.  It's a start, right?

**Comment by jcoyne** [comment]
I'm closing because this is stale. If still an issue please re-open.
